### ISSUE TITLE
Creating Environment

### ISSUE THREAD

**Issue by TolgaTaner** [afet-yonetim-sistemi/ays-iOS#13]
### User story

As I a developer, I need to use environments such as; development, production.

### Acceptance Criteria

- We should change environment using **Settings Bundle**.
- Please, search Setting Bundle if you don't use before other options waste our time during testing.

**Comment by agitrubard** [comment]
@mfd2144 bu issue board üzerinde `DONE` sütununa ilerletilmiş, buradaki issue'yu da kapatalım mı?
