### ISSUE TITLE
Add Notification View

### ISSUE THREAD

**Issue by TolgaTaner** [afet-yonetim-sistemi/ays-iOS#15]
### User story

As I user, I want to see notification view top of the tab bar when is internet connection is unstable.

### Acceptance Criteria

- We should add [Swifty Notification](https://swiftpackageindex.com/abdullahselek/SwiftyNotifications). This is fit. It doesn't block UI. 
- Others are also acceptable.
- Use Swift Package Manager instead of Cocoapods, if it is possible.

**Comment by agitrubard** [comment]
@mfd2144 bu issue board üzerinde `DONE` sütununa ilerletilmiş, buradaki issue'yu da kapatalım mı? Kapatırken label olarak `done` label atayalım.

**Comment by TolgaTaner** [comment]
@agitrubard ilgileniyorum done olmuşlar ile
