### ISSUE TITLE
Creating Custom Reusable Button View

### ISSUE THREAD

**Issue by TolgaTaner** [afet-yonetim-sistemi/ays-iOS#16]
### User story

As I'm contributor, I need to see custom button view to show status, dangerous road, call for help functionality.

### Acceptance Criteria

- It should be a view that is inherited from [CustomNibView](https://github.com/afet-yonetim-sistemi/ays-iOS/blob/main/Driver/Driver/Custom/CustomXibView.swift). It has one image and one label. 
- We should not implement a button because of later iOS button configuration. 
- User can tap inside of the view.
- See the design in [the document](https://github.com/afet-yonetim-sistemi/ays-product/blob/main/doc/mobile/Documents/AYS%20Gereksinim%20Analizi%20Dökümanı%20v1.0.0.docx). It is the right part of map screen.

**Comment by agitrubard** [comment]
@mfd2144 bu issue board üzerinde `DONE` sütununa ilerletilmiş, buradaki issue'yu da kapatalım mı? Kapatırken label olarak `done` label atayalım.
