### ISSUE TITLE
Creating State Manager and Location Manager

### ISSUE THREAD

**Issue by TolgaTaner** [afet-yonetim-sistemi/ays-iOS#20]
### User story

As I'm an user, I need to see the whole location tracking and state tracking in the app.

### Acceptance Criteria

- See [the diagram](https://github.com/afet-yonetim-sistemi/ays-product/blob/main/doc/mobile/Diagrams/Location%20Manager-Online-Flowcharts-Latest.png) to implement it.

**Comment by agitrubard** [comment]
@mfd2144 bu issue board üzerinde `DONE` sütununa ilerletilmiş, buradaki issue'yu da kapatalım mı? Kapatırken label olarak `done` label atayalım.
